@RfidApi_HostAddress = http://localhost:5000
@rfidTag = 123
@rfidTagNew = 125

### Get all items
GET {{RfidApi_HostAddress}}/api/items

### Get single Item
GET {{RfidApi_HostAddress}}/api/items/{{rfidTag}}

### Create new Item
POST {{RfidApi_HostAddress}}/api/items
Content-Type: application/json

{
  "rfid_tag": "{{rfidTagNew}}",
  "name": "New Item",
  "description": "Description for new item",
  "status": "available",
  "certification_code": "CERT123",
  "owner_name": "Owner Name"
}

### Update Item
PUT {{RfidApi_HostAddress}}/api/items/{{rfidTagNew}}
Content-Type: application/json

{
  "name": "Updated Item",
  "description": "Updated description",
  "status": "available",
  "certification_code": "CERT123",
  "owner_name": "Owner Name"
}

### Delete Item
DELETE {{RfidApi_HostAddress}}/api/items/{{rfidTagNew}}

### Create test Item
POST {{RfidApi_HostAddress}}/api/items
Content-Type: application/json

{
  "rfid_tag": "04:55:70:D2:22:6D:80",
  "name": "Test Tag",
  "description": "TestTag",
  "status": "available",
  "certification_code": "none",
  "owner_name": "Tony",
  "last_updated": "2023-01-01T00:00:00Z"
}

### Get all items with owner email filter
GET {{RfidApi_HostAddress}}/api/items?ownerEmail=alice@example.com

### Get all users
GET {{RfidApi_HostAddress}}/api/users

### Create new User
POST {{RfidApi_HostAddress}}/api/users
Content-Type: application/json

{
  "email": "alice@example.com",
  "name": "Alice",
  "role": "user"
}